platform: x64
clone_folder: c:\gopath\src\github.com\ellaism\go-ellaism
os: Visual Studio 2015
environment:
  GOPATH: c:\gopath
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get golang.org/x/sys/windows
build_script:
  - go test ./...
  - go build ./cmd/geth
  - 7z a geth-ellaism-win64.zip geth.exe
  - ps: Get-FileHash geth-ellaism-win64.zip -Algorithm SHA256 | Out-File geth-ellaism-win64.zip.sha256
  - cat geth-ellaism-win64.zip.sha256
artifacts:
  - path: '*.zip'
    name: geth
  - path: '*.zip.sha256'
    name: geth-sha256
deploy:
  artifact: /geth-ellaism-win64\.zip.*/
  auth_token:
    secure: Or4bHgwveQXAjhl+UM1iRUsy5/zbcrk3lUDFFl0nOUyhyuf5PZuvBaEdR2bRW6nv
  draft: true
  on:
    appveyor_repo_tag: true
  provider: GitHub
